### ISSUE TITLE
PCR-GLOBWB 3 development tracking

### ISSUE THREAD

**Issue by BramDr** [UU-Hydro/PCR-GLOBWB_model#44]
This issue will list and track the progress made for PCR-GLOBWB 3. This is a general overview. For each specific item, a separate issue will be made (if necessary) that contains more details.

**Enhancements**

- [ ] Refactoring guidelines
- [ ] PCR-GLOBWB supporting modules refactoring
- [ ] PCR-GLOBWB core modules refactoring

**Features**

- [ ] Flexible landcover type support
- [ ] Flexible soil layers support
- [ ] Zarr file format support
- [ ] Endothermic lake water balance
- [ ] Demand-driven reservoir operations
- [ ] Units switch from [m] to [kg m-2]
